- .github/ISSUE_TEMPLATE/relatar-bug.md
- .github/ISSUE_TEMPLATE/requisitar-funcionalidade.md
- .github/PULL_REQUEST_TEMPLATE.md
Copiei os templates para issue e pull requests do repositório da [Wiki](https://github.com/fga-eps-mds/2019.2-Amika-Wiki/tree/master/.github).
> Adiciona templates para issues e pull requests

- .travis.yml
Foi configurado no Travis CI a supervisão do repositório e adicionado um arquivo como descrito na documentação do Travis CI.
Fixes https://github.com/fga-eps-mds/2019.2-Amika-Backend/issues/7
**Pré Requisito** : https://github.com/fga-eps-mds/2019.2-Amika-Backend/pull/5
**Checklist**
> Integra Travis CI com o projeto

- .travis.yml
- Dockerfile
- docker-compose.yml
Adiciona comunicação dos containers do backend com o do frontend.
Fix #13
**Checklist**
> Adiciona Comunicação de Containers

- Dockerfile.hom
- Procfile
- app.json
- core/settings.py
- docker-compose.yml
- heroku.yml
- requirements.txt
Deploy contínuo dos ambientes do backend feito no Heroku.
[Desenvolvimento](https://amika-backend-dev.herokuapp.com)
[Homologação](https://amika-backend-stg.herokuapp.com)
[Produção](https://amika-backend.herokuapp.com)
Fixes #9 
Fixes #12 
**Checklist**
> Deploy dos Ambientes de PRs, Desenvolvimento, Homologação e Produção do Backend

- .travis.yml
Adicionei o Docker Compose atualizado no Travis CI.
Fixes #19
**Checklist**
> Adiciona Docker Compose no Travis para correção de testes

- core/settings.py
- core/urls.py
- requirements.txt
Criação do token para autenticação do usuário.
https://github.com/fga-eps-mds/2019.2-Amika-Backend/issues/16
**Checklist**
> [US03] - Auto Gerenciar Matricula

- CONTRIBUTING.md
Adicionando o guia de contribuição do projeto de acordo com a wiki oficial.
Guia de contribuição feito seguindo o arquivo na Wiki do projeto.
**Checklist**
> Criando arquivo de contribuição

- LICENSE
Adicionando licença deste repositório e acordo com a licença do projeto
Licença escolhida em acordo com a equipe e já presente na Wiki foi a MIT
**Checklist**
> Adicionando licenca

- README.md
Cria o README deste repositório, com informações referentes a como rodar e contribuir com a aplicação, alem de uma explicação sobre o repositório.
fix #22
**Checklist**
> [DOC19] Criando README

- CODE_OF_CONDUCT.md
Adicionando código de Conduta do projeto para este repositório
Código de conduta conforme o apresentado na Wiki oficial.
**Checklist**
> Criando código de conduta

- Procfile
O Heroku não fazia a migração do banco quando um deployment era feito.
**Checklist**
> HOT-FIX Adiciona migração em deployments

- .github/ISSUE_TEMPLATE/requisitar-funcionalidade.md
Adiciona critérios de aceitação no Template de Issue de Requisitar Funcionalidade no Backend. 
FIX https://github.com/fga-eps-mds/2019.2-Amika-Backend/issues/47
**Checklist**
> Adiciona criterios de aceitacao

- README.md
- seeds.json
Adicionei seeds de Período, Turma, Registos, Alunos
FIX #40 
**Checklist**
> Issue 40 Adiciona seeds

- amika/tests/test_views.py
- amika/urls.py
- amika/views.py
- core/decorators.py
Adicionando funcionalidade de visualizar perfil
FIX #45 
**Checklist**
> Us05 visualizar perfil

- core/urls.py
Removi urn não utilizada.
FIX #61 
**Checklist**
> [HOT-FIX] Remove urn não utilizada

- README.md
Troquei as badges de cobertura de testes.
FIX #35 
**Checklist**
> [HOT-FIX] Mostra cobertura de testes

- amika/permissions.py
Adição do método de autenticação do usuário na funcionalidade de humor
FIX #71 
**Checklist**
> Adicionando método de autenticação do usuário na funcionalidade de humor

- core/urls.py
O acesso a mídias pela url só será possível quando o modo debug tiver acionada.
FIX #86 
**Checklist**
> [HOT-FIX] Corrige vizualização de media diretamente pela url

- .travis.yml
- requirements.txt
Adicionei o token do repositório do Coveralls no Travis.
FIX #35 
**Checklist**
> [HOT-FIX] Bagde de cobertura mostra percentual

- amika/views.py
Consertando o cadastrar aluno
FIX #93 
**Checklist**
> [HOTFIX] Consertando erro de cadastrar aluno

- seeds.json
Criação dos seeds dos humores dos alunos
**Checklist**
> Criando seeds dos humores
